### ISSUE TITLE
INPUT_PARAMETER_NAME is breaking in entrypoint.sh

### ISSUE THREAD

**Issue by expororpranjic** [bomb-on/aws-ssm-to-env#2]
I have done everything like described in the docs and i am getting an error:

`##[warning]Unexpected input 'parameter_name', valid inputs are ['entryPoint', 'args', 'ssm_parameter', 'prefix', 'simple_json', 'jq_filter']`

The parameter_name is unused in the entrypoint.sh, but it is still being checked for it's existence.

- If i declare "parameter_name" in the action, the action is breaking
- If i don't declare "parameter_name" in the action, the entrypoint.sh is breaking with the error "Set SSM parameter name (parameter_name) value."

**Comment by bomb-on** [comment]
Hey, thanks for reporting! I think I see the issue, haven't been using this for a long time since I don't have AWS access anymore. I will have to create a new account, fix those thing and test it out, but in the meantime, as a quick workaround, can you try to set both `ssm_parameter` and `parameter_name` with same values and see if it will work?

**Comment by bomb-on** [comment]
I just fixed the bug, please use `ssm_parameter` from now on, I updated README with proper information, sorry for the confusion. I'll close this issue, feel free to reopen it if needed!
